
// LEADS ACTIONS TYPE
export const GET_LEADS = 'GET_LEADS';
export const DELETE_LEAD = 'DELETE_LEAD';
export const ADD_LEAD = 'ADD_LEAD';

// ERRORS ACTIONS TYPE
export const GET_ERRORS = 'GET_ERRORS';

// MESSAGE ACTIONS TYPE
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

// AUTH ACTION TYPE
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// LOGIN ACTION TYPE
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


// LOGOUT ACTION TYPE
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// REGISTER ACTION TYPE
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


// MAP ACTIONS TYPE
export const GET_MAPS = 'GET_MAPS';
export const ADD_MAP = 'ADD_MAP';
export const DELETE_MAP = 'DELETE_MAP';

