
// LEADS ACTIONS TYPE
export const GET_LEADS = 'GET_LEADS';
export const DELETE_LEAD = 'DELETE_LEAD';
export const ADD_LEAD = 'ADD_LEAD';

// ERRORS ACTIONS TYPE
export const GET_ERRORS = 'GET_ERRORS';

// MESSAGE ACTIONS TYPE
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
